/*
 * Cloudmailer
 *
 * Reference for the public Cloudmailer API calls.  Generated packages use semantic versioning since 2.0.0. The endpoints (v1) itself should always be backwards compatible.  The API uses rate limiting based on requests per minute. Every API response contains the following two headers: 'X-RateLimit-Limit', 'X-RateLimit-Remaining'. `X-RateLimit-Limit` indicates the request limit per minute. `X-RateLimit-Remaining` indicates the amount of available requests.
 *
 * API version: 3.0.0
 * Contact: support@slash2.nl
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudmailer
// ReplacementOrderLine struct for ReplacementOrderLine
type ReplacementOrderLine struct {
	Type string `json:"type,omitempty"`
	Sku string `json:"sku,omitempty"`
	Image string `json:"image,omitempty"`
	Url string `json:"url,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Price int32 `json:"price,omitempty"`
	SalePrice int32 `json:"sale_price,omitempty"`
	Qty int32 `json:"qty,omitempty"`
	Total int32 `json:"total,omitempty"`
	Important bool `json:"important,omitempty"`
}
