/*
 * Cloudmailer
 *
 * Reference for the public Cloudmailer API calls.  Generated packages use semantic versioning since 2.0.0. The endpoints (v1) itself should always be backwards compatible.  The API uses rate limiting based on requests per minute. Every API response contains the following two headers: 'X-RateLimit-Limit', 'X-RateLimit-Remaining'. `X-RateLimit-Limit` indicates the request limit per minute. `X-RateLimit-Remaining` indicates the amount of available requests.
 *
 * API version: 3.0.0
 * Contact: support@slash2.nl
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudmailer
// AutomationTrackIdResponseData struct for AutomationTrackIdResponseData
type AutomationTrackIdResponseData struct {
	Email string `json:"email,omitempty"`
	Subject string `json:"subject,omitempty"`
	PreviewText string `json:"preview_text,omitempty"`
	FromEmail string `json:"from_email,omitempty"`
	FromName string `json:"from_name,omitempty"`
	ReplyToName string `json:"reply_to_name,omitempty"`
	ReplyToEmail string `json:"reply_to_email,omitempty"`
	Replacements map[string]interface{} `json:"replacements,omitempty"`
	AttachmentCount int32 `json:"attachment_count,omitempty"`
	TrackId string `json:"track_id,omitempty"`
	TrackRef string `json:"track_ref,omitempty"`
	DeliveredAt string `json:"delivered_at,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Bounces []AutomationTrackIdResponseDataBounces `json:"bounces,omitempty"`
	Opens []AutomationTrackIdResponseDataOpens `json:"opens,omitempty"`
}
